name = "backend"
compatibility_date = "2023-12-01"
node_compat = true

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiOGQzNDYyODAtYzVjNi00N2I2LTlmY2QtNGMzOGE1MjIxOTZkIiwidGVuYW50X2lkIjoiMmI5NjQ5YjI5YWQzOTI4ZWY4OTk1NjFlOWNhMmM5Mjg4NWE4ZjJlMDNhNWU5MGJmOWQ3MzdiNDk5OTZiNDg5ZiIsImludGVybmFsX3NlY3JldCI6ImY4MWFlMzM4LTE1NDctNDA0Yy1iOGEyLTk5OTA0MTEyZDg0MSJ9.jcPgqmwg4QtI-FZnJMWgZ7Bh4OsAW6E8zuYTA3ACe5E"
JWT_KEY = "123abcde"